// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkokHQ8pyZ1fTJxwqP0aPCRwhDyESAvjw',
    appId: '1:885725401051:web:66dfd391d712001d13e1fe',
    messagingSenderId: '885725401051',
    projectId: 'flutterproject-ebad7',
    authDomain: 'flutterproject-ebad7.firebaseapp.com',
    storageBucket: 'flutterproject-ebad7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpyMDfgBWaYrJNH159EQbwm1LRUdajFk',
    appId: '1:885725401051:android:ee8c4d282541984113e1fe',
    messagingSenderId: '885725401051',
    projectId: 'flutterproject-ebad7',
    storageBucket: 'flutterproject-ebad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLReTHPGqQMVG2kj43-bMOE__rblMjL0',
    appId: '1:885725401051:ios:bf8711eef006943a13e1fe',
    messagingSenderId: '885725401051',
    projectId: 'flutterproject-ebad7',
    storageBucket: 'flutterproject-ebad7.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLReTHPGqQMVG2kj43-bMOE__rblMjL0',
    appId: '1:885725401051:ios:bf8711eef006943a13e1fe',
    messagingSenderId: '885725401051',
    projectId: 'flutterproject-ebad7',
    storageBucket: 'flutterproject-ebad7.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkokHQ8pyZ1fTJxwqP0aPCRwhDyESAvjw',
    appId: '1:885725401051:web:c246b77c614fd71f13e1fe',
    messagingSenderId: '885725401051',
    projectId: 'flutterproject-ebad7',
    authDomain: 'flutterproject-ebad7.firebaseapp.com',
    storageBucket: 'flutterproject-ebad7.appspot.com',
  );
}
